const historiasOscuras = 
{
    "Lyra Howld":
    {
        "El espejo de corteza":
        {
            "Hollowreach":"El bosque respiraba con dificultad aquella noche. Las hojas exhalaban un vapor frío, como si Hollowreach tuviera fiebre. Lyra avanzó entre raíces que se retorcían, guiada por un murmullo que no provenía de los árboles, sino del objeto que llevaba envuelto en tela viva: el Espejo de Corteza.Cuando lo desveló, el cristal de madera vibró como si reconociera su rostro. Pero lo que reflejó no fue a Lyra, sino a otra Lyra, una versión que ya había aceptado convertirse en parte del bosque. Su piel era corteza, sus ojos eran nudos, y su cabello eran ramas finas que se movían con el viento.La otra Lyra levantó la mano desde dentro del espejo. La superficie se onduló como agua.—Ven —susurró con una voz que era mitad humana, mitad raíz—. El bosque no quiere guardianas humanas. Quiere hijas.Lyra retrocedió, pero el bosque avanzó. Las raíces se cerraron detrás de ella, obligándola a mirar. La otra Lyra salió parcialmente del espejo, su brazo hecho de madera viva. Cuando tocó la mejilla de Lyra, la piel de esta empezó a endurecerse, a volverse corteza.El bosque dejó de gritar.Por primera vez en meses, Hollowreach estaba en silencio.Lyra comprendió el horror:El bosque no quería salvarse. Quería reemplazarla.",
            "Aurelia Tempus":"Aurelia Tempus era una ciudad que nunca dormía, pero no porque hubiera vida en cada esquina, sino porque el tiempo mismo se negaba a detenerse. Las calles cambiaban de lugar según la hora, y los relojes gigantes respiraban como pulmones mecánicos.Lyra llegó con el espejo envuelto, sintiendo que cada campanada alteraba su pulso.Cuando lo abrió, el Espejo de Corteza no mostró un solo reflejo, sino cientos.Cientos de Lyra, cada una en una línea temporal distinta. Algunas eran ancianas, otras niñas, otras estaban muertas, otras convertidas en árboles. Todas la miraban con una mezcla de compasión y reproche.Una de ellas, con ojos vacíos, golpeó el cristal desde dentro.La superficie se agrietó.Las demás reflejos comenzaron a golpear también, desesperadas por salir.Lyra retrocedió mientras las grietas se expandían como telarañas temporales. Cada fractura mostraba un futuro donde Hollowreach moría, un pasado donde ella nunca fue guardiana, un presente donde el bosque ya no la necesitaba.El Gran Reloj del centro de la ciudad marcó una hora imposible: 25:61.El espejo explotó en un estallido de madera viva.Lyra huyó entre calles que cambiaban de lugar, mientras cientos de versiones de sí misma la perseguían desde los fragmentos rotos, atrapadas en segundos que no deberían existir.",
            "Maridia Azul":"Maridia Azul brillaba como un corazón marino. Las plataformas gigantes se movían con las mareas, y bajo ellas criaturas luminosas ascendían y descendían como pensamientos del océano.Lyra sintió que el agua la observaba incluso antes de sacar el espejo.Cuando lo hizo, la superficie se llenó de agua.Su reflejo no era humano.Era una versión de Lyra hecha completamente de líquido, con ojos como mareas y cabello que se movía como corrientes profundas.—El océano también recuerda —dijo la versión acuática—. Y te ha estado llamando desde antes de que nacieras.Lyra sintió un tirón en el pecho, como si algo dentro de ella quisiera disolverse. El reflejo extendió la mano desde el espejo, y gotas de agua cayeron al suelo, formando pequeños charcos que susurraban su nombre.Las criaturas luminosas bajo la ciudad se acercaron, atraídas por el espejo. Una de ellas emergió, gigantesca, con un ojo azul que se abrió lentamente.El reflejo sonrió.—El bosque no es el único ser vivo que te reclama.Lyra retrocedió, pero el agua del espejo se derramó, formando una figura líquida que la siguió por las plataformas.El océano había decidido que Lyra era su guardiana…y no aceptaría compartirla.",
            "Elderwood Crown":"Elderwood Crown era un círculo perfecto de árboles colosales, tan altos que ocultaban el cielo. Las calles se abrían y cerraban según la voluntad del bosque, y en el centro se alzaba la Corona Arbórea, un árbol gigantesco que actuaba como templo y trono.Lyra sintió que el lugar la reconocía.Cuando abrió el Espejo de Corteza, vio una versión de sí misma sentada en la Corona Arbórea.Era reina.Pero no humana.Su cuerpo estaba fusionado con el árbol central. Sus piernas eran raíces profundas, sus brazos ramas que sostenían luz verde. Sus ojos eran pozos de savia.La otra Lyra sonrió con una calma inquietante.—Elderwood Crown ya te eligió —dijo—. No como guardiana. Como soberana.Las calles vivas se cerraron detrás de Lyra, obligándola a avanzar hacia el espejo. El árbol central vibró, como si esperara su llegada.La otra Lyra extendió la mano desde el cristal, y la corteza del árbol respondió, abriéndose como una boca vegetal.Lyra sintió que el bosque entero la estaba midiendo.Evaluando si era digna.No para gobernarlo…sino para alimentarlo.",
        },

        "La corona de espinas vivas":
        {
            "Hollowreach":"La corona parecía dormida cuando Lyra la encontró entre raíces negras, pero al tocarla sintió un latido. No era suyo. Era del bosque. Las espinas se movieron como dedos buscando piel, y Lyra comprendió que aquel artefacto no otorgaba autoridad: exigía sacrificio.Aun así, se la colocó. Hollowreach gritaba demasiado fuerte como para ignorarlo.El primer impacto fue un silencio absoluto. Las voces de los árboles, los lamentos de las raíces, los susurros de los animales… todo se apagó. Lyra sintió alivio por un instante, hasta que notó cómo la corona empezaba a hundirse en su cráneo. Las espinas se clavaron, pero no para herirla: para enraizarse.El bosque respondió de inmediato. Las raíces se levantaron como serpientes, obedeciendo cada respiración de Lyra. Podía mover árboles enteros con un gesto. Podía cerrar caminos, abrir grietas, detener el avance de la muerte que consumía Hollowreach.Pero cada orden tenía un precio.La corona bebía de ella.Primero minutos de vida. Luego horas. Luego días.Cuando intentó quitársela, las espinas ya habían crecido hacia dentro, buscando su corazón.Lyra comprendió que el bosque no quería una guardiana.Quería una ofrenda viva.",
            "Aurelia Tempus":"Aurelia Tempus vibraba con miles de relojes respirando al unísono. La corona reaccionó al instante, como si la ciudad temporal fuera un festín. Las espinas se tensaron, ansiosas, y Lyra sintió cómo su pulso se aceleraba sin control.Cada campanada del Gran Reloj le robaba un año de vida.Cada segundo era una negociación con la muerte.Pero a cambio, Lyra podía hacer algo imposible:detener el tiempo del bosque, aunque estuviera lejos.Podía congelar la muerte que avanzaba por Hollowreach, suspender la corrupción, mantener vivas raíces que ya deberían estar muertas.Era un poder absoluto… y una condena.La corona floreció con cada uso, brotando pequeñas hojas negras que caían al suelo como ceniza. Lyra envejecía y rejuvenecía en ciclos dolorosos, atrapada en un vaivén temporal que la desgarraba.La ciudad la observaba.Los relojes la medían.El tiempo la juzgaba.Cuando el Gran Reloj marcó una hora imposible, la corona se abrió como una flor de espinas.Lyra sintió cómo cien años se evaporaban de su cuerpo en un solo latido.La ciudad quedó congelada.Ella quedó vacía.Aurelia Tempus no quería su vida.Quería su tiempo.",
            "Maridia Azul":"La bruma marina envolvió la corona, y las espinas reaccionaron como si despertaran de un sueño profundo. Absorbieron humedad, se hincharon, y comenzaron a moverse con un ritmo que no era terrestre.Lyra sintió que algo dentro del océano respondía.Cuando se colocó la corona, las mareas cambiaron.Las plataformas de Maridia Azul se inclinaron, como si la ciudad flotante se arrodillara ante ella. Las criaturas luminosas bajo el agua ascendieron, formando un círculo alrededor de la plataforma donde Lyra estaba.El océano la reconocía.La aceptaba.La reclamaba.Pero la corona tenía su propio plan.Las espinas crecieron hacia abajo, buscando su corazón.Cada vez que Lyra controlaba una corriente, una ola, una criatura marina, la corona drenaba un recuerdo.Primero pequeñosLuego importantes.Luego esenciales.Cuando una marea gigantesca se levantó obedeciendo su gesto, Lyra sintió que olvidaba el rostro de su madre.Cuando calmó una tormenta, olvidó su propio nombre por un instante.La corona floreció, satisfecha.El océano la quería como guardiana.La corona la quería como sacrificio.",
            "Elderwood Crown":"Elderwood Crown reaccionó a la corona como si fuera una reliquia perdida. Los árboles colosales se inclinaron, las calles vivas se abrieron, y la Corona Arbórea vibró con un sonido profundo, casi humano.Lyra sintió que el bosque entero la estaba esperando.Cuando se colocó la corona, las espinas se fusionaron con la corteza viva del lugar. No la herían: la integraban.Lyra sintió raíces creciendo bajo su piel, extendiéndose por sus brazos, conectándola al árbol central.Por primera vez, comprendió el lenguaje completo del bosque.No solo sus voces.También sus intenciones.Elderwood Crown no quería una reina.Quería un corazón nuevo.El árbol central estaba muriendo, y la corona era el puente para reemplazarlo.Lyra sintió cómo su vida se drenaba hacia el tronco gigantesco, alimentándolo, rejuveneciéndolo.El bosque floreció.Ella se marchitó.Cuando intentó quitarse la corona, las espinas ya eran parte de ella.El árbol central abrió una grieta en su corteza, como una boca esperando alimento.Lyra comprendió que Elderwood Crown no buscaba salvarse.Buscaba renacer…con ella como raíz principal.",
        },

        "La copa del cielo":
        {
            "Hollowreach":"Lyra encontró la Copa del Cielo enterrada bajo un círculo de raíces negras, como si el bosque hubiera intentado ocultarla de sí mismo. El artefacto vibraba con una luz tenue, casi tímida, pero cuando Lyra lo sostuvo, las voces del bosque se callaron. No era silencio natural: era un silencio impuesto, como si algo más poderoso hubiera ordenado a Hollowreach guardar silencio.Lyra vertió agua del bosque en la copa. La savia líquida se volvió dorada, y al beberla, el mundo se fracturó. Vio a los seres sobrenaturales que vivían entre las raíces: figuras hechas de madera viva, sombras con ojos verdes, criaturas que se movían entre los árboles como pensamientos.No eran guardianes.No eran protectores.Eran depredadores antiguos, y el bosque era su cuerpo.Uno de ellos se acercó a Lyra en la visión, con un rostro hecho de corteza y dientes de raíz.—Ahora puedes vernos —dijo—. Y eso significa que podemos verte.Lyra cayó de rodillas cuando la visión terminó. El bosque volvió a gritar, pero ya no eran voces: eran advertencias.La copa había revelado algo que Hollowreach nunca quiso que ella supiera.Y ahora, aquello que vivía bajo las raíces sabía que Lyra podía verlos.",
            "Aurelia Tempus":"Aurelia Tempus reaccionó a la copa como si fuera un intruso temporal. Las torres de cristal reflejaron la luz del artefacto, multiplicándola en miles de futuros posibles. Lyra sintió que cada paso que daba alteraba la ciudad, como si el tiempo mismo se apartara para dejarla pasar.La copa se llenó sola con luz líquida, un brillo que parecía hecho de segundos rotos. Cuando Lyra bebió, vio futuros donde ella no existía. En todos ellos, la ciudad era más estable, más ordenada, más perfecta.El Gran Reloj vibró, como si aprobara esa visión.Lyra sintió un frío profundo.La copa le estaba mostrando que su existencia era una anomalía temporal.Que Hollowreach la había elegido… pero el tiempo no.Cuando la visión terminó, las calles cambiaron de lugar, alejándola del centro. La ciudad la estaba expulsando, reordenando su estructura para mantenerla lejos del Gran Reloj.Aurelia Tempus no quería matarla.Quería borrarla.",
            "Maridia Azul":"La copa se llenó con agua luminosa apenas Lyra la acercó al borde de la plataforma. El océano parecía reconocerla, como si supiera que ella era una guardiana de otro ser vivo.Cuando bebió, la luz marina la atravesó como un rayo.Lyra vio criaturas gigantes respirando bajo la ciudad. No eran animales: eran memorias vivas del océano, pensamientos colosales que se movían entre corrientes profundas. Una de ellas abrió un ojo azul, tan grande como una casa, y la miró directamente.Lyra sintió que el océano pronunciaba su nombre.La visión cambió.Vio una marea gigantesca levantándose, devorando ciudades enteras.Vio a la criatura colosal ascendiendo, despertando.Vio que ella estaba en el centro de todo, como un punto de unión entre bosque y mar.Cuando la visión terminó, el agua bajo la ciudad brillaba con más intensidad.El océano no quería destruirla.Quería reclamarla.",
            "Elderwood Crown":"La copa se llenó con savia dorada apenas Lyra entró en la ciudad circular. Elderwood Crown vibró, como si reconociera el artefacto. Las calles vivas se abrieron, guiándola hacia la Corona Arbórea.El árbol central parecía esperar.Cuando Lyra bebió, vio el espíritu del árbol. Era gigantesco, hecho de luz verde y raíces infinitas.—El bosque muere —dijo—. Pero puede renacer.Lyra vio cómo su vida se entrelazaba con la del árbol, cómo su sangre podía convertirse en savia, cómo su alma podía convertirse en raíz.El espíritu le ofreció un pacto:su vida a cambio de la supervivencia del bosque.Lyra no respondió.Pero el árbol sí.Las raíces se movieron bajo sus pies, acercándose, evaluándola, midiendo su valor como sacrificio.La copa había revelado la verdad:Elderwood Crown no quería una guardiana.Quería un corazón nuevo.",
        },

        "La llama de hueso":
        {
            "Hollowreach":"La llama blanca ardía sin consumir el hueso que la contenía. Lyra la sostuvo con cuidado, sintiendo que el fuego la observaba. Cuando la acercó a las raíces del bosque, Hollowreach reaccionó como si hubiera visto un enemigo.La llama reveló zonas muertas del bosque que seguían moviéndose. Raíces negras que se retorcían como gusanos, troncos huecos que respiraban, sombras vegetales que se apartaban del fuego como animales asustados.Lyra comprendió que la muerte en Hollowreach no era natural.Era intencional.Cuando acercó más la llama, las raíces muertas se apartaron, temblando.Algo dentro del bosque temía ese fuego.Algo que no era vegetal.Algo que vivía entre las raíces muertas, alimentándose de ellas.Lyra sintió un susurro detrás de ella.No era el bosque.Era aquello que la llama estaba revelando.",
            "Aurelia Tempus":"La llama reaccionó a la ciudad temporal como si pudiera ver horas muertas. Cuando Lyra la levantó, el fuego blanco reveló relojes que deberían estar rotos… pero seguían latiendo.Segundos que deberían haber desaparecido seguían existiendo, atrapados en bucles invisibles.Lyra vio sombras humanas atrapadas en esos segundos rotos. Personas que vivían en horas que ya habían pasado, repitiendo movimientos sin saber que estaban muertas temporalmente.Una de ellas se giró hacia Lyra.Tenía ojos vacíos.Tenía la voz del bosque.La llama rugió, como si reconociera a la sombra.La ciudad tembló.El tiempo se fracturó por un instante.Lyra comprendió que Aurelia Tempus no solo manipulaba el tiempo.Lo devoraba.",
            "Maridia Azul":"La llama reveló criaturas marinas que deberían haber muerto hace siglos. Algunas tenían esqueletos visibles, otras cuerpos transparentes, otras ojos apagados que aún se movían.El océano guardaba cadáveres que respiraban.Una de las criaturas ascendió, atraída por la luz blanca. Era gigantesca, hecha de hueso y luz azul. Cuando emergió, Lyra sintió que el océano rugía dentro de ella.La criatura abrió la boca.No para devorarla.Para hablar.La llama vibró, como si reconociera a la criatura.Lyra sintió que el océano tenía secretos que solo el fuego blanco podía revelar.Y que algunos de esos secretos no querían ser vistos.",
            "Elderwood Crown":"La llama reveló que el árbol central tenía un corazón muerto… pero seguía latiendo.Lyra acercó el fuego, y el árbol rugió.No con voz vegetal.Con voz humana.Las raíces se levantaron, formando un círculo alrededor de ella. La corteza del árbol se abrió, mostrando un hueco oscuro donde debería haber savia.La llama iluminó el interior.Lyra vio huesos.Humanos.Fusionados con la madera.El árbol central no era solo un templo.Era un sepulcro vivo.La llama rugió, revelando que el corazón muerto del árbol seguía latiendo porque estaba hecho de alguien.Alguien que el bosque no había dejado morir.",
        },
    },

    "Faye Silver":
    {
        "El espejo de corteza":
        {
            "Hollowreach":"El bosque respiraba como un animal herido cuando Faye llegó. No era su mundo, pero el tiempo la había traído allí, como si Hollowreach necesitara una intrusa para revelar sus secretos. El Espejo de Corteza vibraba en sus manos, ansioso, como si reconociera su obsesión por alterar realidades.Cuando lo abrió, el reflejo no mostró a Faye tal como era, sino a una versión que nunca perdió a su hermana. Esa Faye tenía los ojos llenos de luz, una sonrisa tranquila, y manos limpias de culpa.Pero había algo más.Esa versión feliz tenía una sombra detrás: una criatura hecha de raíces negras, que se alimentaba de su alegría.La otra Faye habló:—Este futuro existe. Solo tienes que arrancar el tuyo.El bosque tembló. Las raíces se levantaron, atraídas por la versión alternativa. Faye sintió un tirón en el pecho, como si su propio tiempo quisiera dividirse.El espejo empezó a absorberla, intentando reemplazarla por la versión perfecta.Faye retrocedió, pero el bosque cerró los caminos.El espejo quería darle una vida sin dolor.El bosque quería una guardiana temporal.Y ambas cosas exigían lo mismo:que Faye dejara de existir en su línea original.",
            "Aurelia Tempus":"Aurelia Tempus era el único lugar donde Faye se sentía en casa. Las torres de cristal temporal reflejaban futuros posibles, y las calles cambiaban según la hora. Allí, el tiempo era una sustancia que podía moldear, romper, o beber.El espejo reaccionó de inmediato.Cuando lo abrió, no vio un reflejo, sino miles.Miles de Fayes, cada una en una línea temporal distinta.Algunas eran ancianas, otras niñas, otras estaban muertas, otras convertidas en sombras atrapadas en segundos rotos.Todas la miraban con desesperación.Una de ellas golpeó el cristal desde dentro.Luego otra.Luego todas.El espejo se agrietó, y las versiones alternativas intentaron salir, como si quisieran ocupar su lugar en la línea principal.Faye sintió que el tiempo se fracturaba alrededor de ella, creando bucles, duplicados, ecos.El Gran Reloj marcó una hora imposible.Las versiones alternativas comenzaron a escapar por las grietas.Faye huyó entre calles que cambiaban de lugar, mientras cientos de ella misma la perseguían, cada una con un destino distinto que quería imponerse sobre el suyo.",
            "Maridia Azul":"La ciudad flotante brillaba como un corazón marino. Las plataformas se movían con las mareas, y bajo ellas criaturas luminosas ascendían y descendían como pensamientos del océano.Faye sintió que el agua tenía memoria.Memoria… y rencor.Cuando abrió el espejo, la superficie se llenó de agua.Su reflejo era una versión de sí misma hecha de líquido, con ojos como corrientes profundas y cabello que se movía como mareas temporales.—El océano recuerda mejor que tú —dijo la versión acuática—. Y recuerda lo que perdiste.El agua del espejo se derramó, formando una figura líquida que caminó hacia ella. Las criaturas luminosas se acercaron, atraídas por el artefacto.Una de ellas emergió, gigantesca, con un ojo azul que se abrió lentamente.El reflejo sonrió.—Tu dolor es una marea. Y las mareas siempre vuelven.Faye retrocedió, pero el agua la siguió, intentando arrastrarla hacia un futuro donde su hermana vivía… y donde ella debía convertirse en parte del océano para alcanzarla.",
            "Elderwood Crown":"Elderwood Crown era un círculo perfecto de árboles colosales. Las calles vivas se abrían y cerraban según la voluntad del bosque, y la Corona Arbórea vibraba con un sonido profundo, casi humano.El espejo reaccionó como si reconociera el lugar.Cuando lo abrió, vio una versión de sí misma fusionada con el árbol central.Esa Faye tenía raíces en lugar de piernas, brazos hechos de ramas, y ojos llenos de savia.Era la guardiana temporal del bosque.Era su corazón.La otra Faye habló:—Aquí, el tiempo no es línea. Es raíz.—¿Y yo? —preguntó Faye.—Eres el sacrificio que permite que el bosque recuerde.Las raíces se levantaron, formando un círculo alrededor de ella. El árbol central abrió una grieta en su corteza, como una boca esperando alimento.El espejo vibró, intentando absorberla.Faye comprendió que Elderwood Crown no quería una alquimista.Quería un reloj vivo.",
        },
    
        "La corona de espinas vivas":
        {
            "Hollowreach":"La corona parecía dormida, pero al tocarla Faye sintió un latido. No era vegetal. Era temporal. Las espinas vibraban como agujas de reloj, marcando segundos que no existían.Cuando se la colocó, el bosque gritó.La corona aceleró su vida y la retrocedió en ciclos dolorosos. Faye vivía y moría en segundos, atrapada en un vaivén temporal que la desgarraba.Pero a cambio, podía controlar el tiempo del bosque.Podía detener la muerte que avanzaba por Hollowreach.Podía congelar raíces, suspender la corrupción, mantener vivas zonas que ya deberían estar muertas.El bosque la observaba, fascinado.Las raíces se movían obedeciendo su respiración.Pero cada uso drenaba años de su vida.Cuando intentó quitarse la corona, las espinas ya habían echado raíces en su cráneo.El bosque no quería una guardiana.Quería un reloj humano.",
            "Aurelia Tempus":"La corona reaccionó a la ciudad temporal como si fuera su hogar. Cada campanada del Gran Reloj le robaba años.Cada segundo era una negociación con la muerte.Pero a cambio, Faye podía detener el tiempo de toda la ciudad.Podía congelar calles, torres, personas, relojes.Podía suspender la realidad.La corona floreció con cada uso, brotando hojas negras que caían como ceniza. Faye envejecía y rejuvenecía en ciclos dolorosos, atrapada en un vaivén temporal que la desgarraba.La ciudad la observaba.El tiempo la juzgaba.Cuando el Gran Reloj marcó una hora imposible, la corona se abrió como una flor de espinas.Faye sintió cómo cien años se evaporaban de su cuerpo en un solo latido.Aurelia Tempus no quería su vida.Quería su tiempo.",
            "Maridia Azul":"La bruma marina envolvió la corona, y las espinas reaccionaron como si despertaran de un sueño profundo. Absorbieron humedad, se hincharon, y comenzaron a moverse con un ritmo que no era terrestre.Faye sintió que algo dentro del océano respondía.Cuando se la colocó, las mareas cambiaron.Las plataformas se inclinaron.Las criaturas luminosas ascendieron.El océano la reconocía.Pero la corona tenía su propio plan.Las espinas crecieron hacia abajo, buscando su corazón.Cada vez que Faye controlaba una corriente, una ola, una criatura marina, la corona drenaba un recuerdo.Primero pequeños.Luego importantes.Luego esenciales.Cuando calmó una tormenta, olvidó el rostro de su hermana por un instante.La corona floreció, satisfecha.El océano la quería como guardiana.La corona la quería como sacrificio.",
            "Elderwood Crown":"Elderwood Crown reaccionó a la corona como si fuera una reliquia perdida. Los árboles colosales se inclinaron, las calles vivas se abrieron, y la Corona Arbórea vibró con un sonido profundo, casi humano.Faye sintió que el lugar la estaba esperando.Cuando se la colocó, las espinas se fusionaron con la corteza viva del lugar. No la herían: la integraban.Faye sintió raíces creciendo bajo su piel, extendiéndose por sus brazos, conectándola al árbol central.Por primera vez, comprendió el lenguaje completo del bosque.Elderwood Crown no quería una reina.Quería un corazón nuevo.El árbol central estaba muriendo, y la corona era el puente para reemplazarlo.Las raíces se movieron bajo sus pies, acercándose, evaluándola, midiendo su valor como sacrificio.El bosque no quería su magia.Quería su tiempo vital.",
        },

        "La copa del cielo":
        {
            "Hollowreach":"La copa vibraba con una luz tenue, casi tímida, pero cuando Faye la sostuvo, las voces del bosque se callaron.No era silencio natural.Era un silencio impuesto.Faye vertió savia en la copa.La savia se volvió dorada.Al beber, vio el momento exacto en que Hollowreach empezó a morir.No fue accidente.No fue enfermedad.Fue asesinato.Vio sombras humanas cortando raíces vivas, quemando troncos, enterrando algo bajo el bosque.Algo que no debía despertar.Cuando la visión terminó, el bosque gritó.No eran voces.Eran advertencias.La copa había revelado la verdad.Y ahora aquello que vivía bajo las raíces sabía que Faye lo había visto.",
            "Aurelia Tempus":"La copa se llenó sola con luz líquida.Cuando Faye bebió, vio futuros donde ella salvaba la ciudad… y futuros donde la destruía.En todos, el tiempo la temía.El Gran Reloj vibró, como si reconociera su poder.Las calles cambiaron de lugar, guiándola hacia el centro.La ciudad quería mostrarle algo.Faye vio quién manipulaba el Gran Reloj desde las sombras.No era humano.No era temporal.Era una criatura hecha de segundos rotos, un ser que vivía entre campanadas.La copa reveló su rostro.El tiempo rugió.",
            "Maridia Azul":"La copa se llenó con agua luminosa.Al beber, Faye vio el futuro del océano: una marea que devoraría ciudades enteras.Vio criaturas gigantes ascendiendo.Vio la ciudad flotante hundiéndose.Y vio que ella era la causa.La copa vibró, mostrando un futuro donde Faye manipulaba las mareas temporales, creando una ola que alteraba siglos.Una ola que despertaba a la criatura colosal.Cuando la visión terminó, el océano brillaba con más intensidad.El mar no quería destruirla.Quería usarla.",
            "Elderwood Crown":"La copa se llenó con savia dorada.Al beber, Faye vio el espíritu del árbol central.Era gigantesco, hecho de luz verde y raíces infinitas.—Puedo traerla de vuelta —dijo el espíritu.Faye sintió que su corazón se detenía.—¿A mi hermana?—Sí. Pero a cambio… tú.Las raíces se movieron, acercándose.El árbol quería su tiempo.Su vida.Su alma.La copa había revelado el pacto.Y el bosque esperaba su respuesta.",
        },

        "La llama de hueso":
        {
            "Hollowreach":"La llama reveló zonas muertas del bosque que seguían moviéndose.Raíces negras que respiraban.Sombras vegetales que se apartaban del fuego.Faye comprendió que la muerte en Hollowreach no era natural.Era intencional.Alguien había matado partes del bosque… y esas partes seguían vivas.Cuando acercó más la llama, las raíces muertas se apartaron, temblando.Algo dentro del bosque temía ese fuego.Algo que no era vegetal.La llama rugió.El bosque respondió.Y Faye sintió un susurro detrás de ella.No era el bosque.Era aquello que la llama estaba revelando.",
            "Aurelia Tempus":"La llama reveló horas muertas que seguían latiendo.Segundos rotos.Minutos atrapados.Sombras humanas viviendo en tiempos que ya habían pasado.Una de ellas se giró hacia Faye.Tenía la voz de su hermana.La llama rugió, como si reconociera a la sombra.El tiempo tembló.La ciudad vibró.Faye comprendió que Aurelia Tempus no solo manipulaba el tiempo.Lo devoraba.",
            "Maridia Azul":"La llama reveló criaturas marinas muertas que seguían nadando.Algunas tenían esqueletos visibles.Otras cuerpos transparentes.Otras ojos apagados que aún se movían.Una de ellas ascendió, atraída por la luz blanca.Era gigantesca, hecha de hueso y luz azul.La criatura abrió la boca.No para devorarla.Para hablar.La llama vibró, reconociendo a la criatura.El océano rugió.Y Faye sintió que el mar tenía secretos que solo el fuego blanco podía revelar.",
            "Elderwood Crown":"La llama reveló que el árbol central tenía un corazón muerto… pero seguía latiendo.Faye acercó el fuego, y el árbol rugió.No con voz vegetal.Con voz humana.Las raíces se levantaron, formando un círculo alrededor de ella.La corteza se abrió, mostrando un hueco oscuro lleno de huesos humanos fusionados con madera.El árbol central no era un templo.Era un sepulcro vivo.La llama rugió, revelando que el corazón muerto del árbol seguía latiendo porque estaba hecho de alguien.Alguien que el bosque no había dejado morir.",
        }
    },

    "Orion River":
    {
        "El espejo de corteza":
        {
            "Hollowreach":"El bosque respiraba con un ritmo que Orion no reconocía. No era el pulso vegetal de Hollowreach, sino algo más profundo, más antiguo, como si las raíces estuvieran imitando el movimiento del océano. El espejo vibraba en sus manos, húmedo, como si hubiera sido sumergido en agua minutos antes.Cuando lo abrió, la superficie se onduló como un lago.Su reflejo no era humano.Era un río.Un río que serpenteaba entre raíces vivas, con ojos hechos de corriente y un rostro formado por espuma. El reflejo habló con una voz líquida:—El agua también es bosque. Y tú eres ambas cosas.Orion sintió un tirón en el pecho, como si su sangre quisiera abandonar su cuerpo para convertirse en corriente. Las raíces se levantaron, formando canales que imitaban cauces. El bosque estaba intentando absorberlo, convertirlo en parte de su sistema vivo.El reflejo extendió una mano hecha de agua.Cuando lo tocó, Orion sintió que su piel se volvía líquida.El bosque gritó.El océano respondió.Hollowreach no quería un guardián.Quería un río vivo.",
            "Aurelia Tempus":"Aurelia Tempus vibraba con miles de relojes respirando al unísono. Orion sintió que el tiempo tenía sabor salado allí, como si la ciudad hubiera absorbido fragmentos del océano.El espejo reaccionó de inmediato.Cuando lo abrió, vio una versión de sí mismo viviendo en un futuro donde el mar había devorado la ciudad temporal. Las torres de cristal estaban sumergidas, y criaturas luminosas nadaban entre los relojes rotos.Su reflejo tenía ojos azules como la entidad colosal que había visto en las profundidades.—Tú la despertaste —dijo el reflejo—. Y ahora quiere más.El espejo se llenó de agua.Las calles cambiaron de lugar, formando canales.El tiempo se volvió líquido.Orion sintió que la ciudad estaba intentando arrastrarlo hacia un futuro donde él era el detonante de una marea temporal.Un futuro donde el océano devoraba el tiempo.El reflejo sonrió.—El mar no olvida. Y tú eres su memoria.",
            "Maridia Azul":"Maridia Azul brillaba como un corazón marino. Las plataformas se movían con las mareas, y bajo ellas criaturas luminosas ascendían y descendían como pensamientos del océano.Orion sintió que el agua lo reconocía.Cuando abrió el espejo, la superficie se llenó de luz azul.Su reflejo era la criatura colosal.La misma que había visto en las profundidades.La misma que le había revelado que el océano era un ser vivo.—El océano te reclama —dijo la entidad desde el espejo—. No como hijo. Como extensión.El agua del espejo se derramó, formando una figura líquida que caminó hacia él. Las criaturas luminosas se acercaron, formando un círculo alrededor de la plataforma.El mar estaba convocando.Orion sintió que su respiración se sincronizaba con las mareas.Que su corazón latía como una ola.Que su cuerpo quería disolverse.El océano no quería un guardián.Quería un avatar.",
            "Elderwood Crown":"Elderwood Crown era un círculo perfecto de árboles colosales. Orion sintió que el bosque lo observaba como si fuera un intruso marino.El espejo reaccionó como si quisiera unir ambos mundos.Cuando lo abrió, vio una versión de sí mismo convertido en río que alimentaba el árbol central.Esa versión tenía ojos de agua y brazos hechos de corriente.Era parte del bosque.Y el bosque era parte de él.—El bosque también necesita océanos —dijo el reflejo.Las raíces se levantaron, formando cauces.El árbol central vibró, como si quisiera absorberlo.Orion sintió que su cuerpo se volvía líquido, que su sangre quería fluir hacia la corteza viva.El bosque no quería un guardián.Quería un río eterno.",
        },

        "La corona de espinas vivas":
        {
            "Hollowreach":"La corona parecía seca, pero cuando Orion la tocó, las espinas se humedecieron.Absorbieron agua de su piel.Se despertaron.Cuando se la colocó, las raíces del bosque reaccionaron como si hubieran encontrado un nuevo cauce.Las espinas intentaron convertir su cuerpo en raíz.Orion respondió con agua.Las espinas se humedecieron más, creciendo hacia dentro, buscando su corazón.El bosque quería absorberlo, convertirlo en parte de su sistema vivo.Orion sintió que su sangre se volvía savia.Cada vez que intentaba resistirse, la corona drenaba parte de su vida.Cada vez que intentaba controlarla, drenaba parte de su agua interior.El bosque no quería un guardián.Quería un tronco vivo.",
            "Aurelia Tempus":"La corona reaccionó a la ciudad temporal como si fuera un reloj vegetal.Cada campanada del Gran Reloj drenaba agua de su cuerpo.Orion sintió que el océano dentro de él se agitaba, intentando romper la corona desde dentro.Pero la corona tenía su propio plan.Las espinas vibraban como agujas de reloj.El tiempo se volvía líquido.Orion envejecía y rejuvenecía en ciclos dolorosos.La ciudad lo observaba.El tiempo lo medía.El océano rugía dentro de él.Cuando el Gran Reloj marcó una hora imposible, la corona floreció.Orion sintió que su vida se evaporaba como agua en un desierto temporal.La ciudad no quería su poder.Quería su tiempo líquido.",
            "Maridia Azul":"La bruma marina envolvió la corona, y las espinas reaccionaron como si despertaran de un sueño profundo.Absorbieron humedad.Se hincharon.Se movieron.Cuando Orion se la colocó, las mareas cambiaron.Las plataformas se inclinaron.Las criaturas luminosas ascendieron.El océano lo reconocía.Pero la corona tenía hambre.Las espinas crecieron hacia dentro, buscando su corazón.Cada vez que Orion controlaba una corriente, una ola, una criatura marina, la corona drenaba parte de su agua interior.Cuando calmó una tormenta, sintió que olvidaba el sonido del océano por un instante.La corona floreció, satisfecha.El mar lo quería como guardián.La corona lo quería como sacrificio líquido.",
            "Elderwood Crown":"Elderwood Crown reaccionó a la corona como si fuera una reliquia perdida.Los árboles colosales se inclinaron.Las calles vivas se abrieron.La Corona Arbórea vibró.Cuando Orion se la colocó, las espinas se fusionaron con la corteza viva del lugar.No lo herían: lo integraban.Orion sintió raíces creciendo bajo su piel, extendiéndose por sus brazos, conectándolo al árbol central.El bosque quería convertirlo en río.En savia.En raíz.Elderwood Crown no quería un guardián.Quería un corazón líquido.",
        },

        "La copa del cielo":
        {
            "Hollowreach":"Orion vertió agua del océano en la copa.El bosque gritó.La savia se agitó.Las raíces temblaron.Cuando bebió, vio que Hollowreach tenía raíces que llegaban hasta el mar.Vio corrientes subterráneas conectando ambos mundos.Vio criaturas marinas moviéndose entre raíces vivas.El bosque no era solo bosque.Era parte del océano.Y el océano era parte del bosque.La copa vibró.El agua dentro de ella se volvió verde.Orion sintió que su cuerpo quería dividirse entre ambos mundos.Hollowreach no quería un guardián.Quería un puente vivo.",
            "Aurelia Tempus":"La copa se llenó sola con luz líquida.Cuando Orion bebió, vio futuros donde el océano devoraba la ciudad.Vio torres sumergidas.Vio relojes rotos flotando como cadáveres.En todos esos futuros, él era el detonante.El punto de unión entre mar y tiempo.El error que el tiempo quería corregir.La copa vibró.El agua dentro de ella se volvió azul oscuro.Orion sintió que el tiempo quería arrastrarlo hacia un futuro donde él era marea.Aurelia Tempus no quería su vida.Quería su corriente temporal.",
            "Maridia Azul":"La copa se llenó con agua luminosa.Cuando Orion bebió, vio la criatura colosal despertando.Vio su ojo azul abriéndose.Vio su cuerpo ascendiendo.El océano rugió.Las plataformas temblaron.Las criaturas luminosas ascendieron.La copa vibró.El agua dentro de ella se volvió blanca.Orion sintió que el océano quería usarlo como llave para abrir algo que llevaba siglos dormido.El mar no quería un guardián.Quería un despertador.",
            "Elderwood Crown":"La copa se llenó con savia dorada.Cuando Orion bebió, vio que el árbol central tenía un océano dentro.Un océano pequeño.Un océano vivo.Un océano que respiraba.Las raíces se movieron, formando cauces.El árbol vibró.El bosque rugió.La copa reveló que Elderwood Crown no era solo bosque.Era un mar vegetal.Y Orion era su hijo.",
        },

        "La llama de hueso":
        {
            "Hollowreach":"La llama reveló raíces muertas que seguían moviéndose.Orion las tocó con agua.Las raíces intentaron beberlo.El bosque tembló.La llama rugió.El agua dentro de él se agitó.Orion comprendió que la muerte en Hollowreach no era natural.Era un parásito.Y ese parásito quería beberlo.",
            "Aurelia Tempus":"La llama mostró horas muertas que seguían latiendo.Orion vio sombras marinas atrapadas en segundos rotos.Criaturas hechas de tiempo líquido.Una de ellas se acercó.Tenía ojos azules.Tenía la voz del océano.El tiempo rugió.La llama respondió.Aurelia Tempus no quería su vida.Quería su corriente temporal.",
            "Maridia Azul":"La llama reveló criaturas marinas muertas que seguían nadando.Una tenía la voz del océano.Otra tenía su rostro.El mar rugió.La llama respondió.Orion sintió que el océano tenía cadáveres que aún respiraban.Y que algunos querían reemplazarlo.",
            "Elderwood Crown":"La llama reveló que el árbol central tenía un corazón muerto… pero seguía latiendo.Orion escuchó un latido idéntico al del océano.Un latido marino.Un latido vegetal.El árbol rugió.El mar respondió.Orion sintió que ambos mundos querían fusionarse dentro de él.Elderwood Crown no quería un guardián.Quería un océano vivo.",
        }
    },

    "Aenar Wood":
    {
        "El espejo de corteza":
        {
            "Hollowreach":"Aenar regresó a Hollowreach con el peso de un legado que nunca quiso. El bosque respiraba como un animal moribundo, y cada exhalación parecía pronunciar su apellido: Woodbound.El Espejo de Corteza vibraba en sus manos, como si reconociera la sangre que corría por sus venas.Cuando lo abrió, vio una versión de sí mismo completamente fusionada con el bosque.Esa versión tenía piel de corteza, ojos de savia, y brazos que se extendían como ramas infinitas.Era el guardabosques perfecto.Era lo que su familia había sido durante siglos.El reflejo habló con una voz que era mitad humana, mitad raíz:—Este es tu destino. No puedes huir de él.Las raíces se levantaron, formando un círculo alrededor de Aenar.El bosque avanzó.El espejo retrocedió, como si quisiera absorberlo.Aenar sintió que su cuerpo quería dividirse, que su piel quería endurecerse, que su alma quería enraizarse.El bosque no quería un descendiente.Quería un reemplazo.",
            "Aurelia Tempus":"Aurelia Tempus era un lugar donde el tiempo se doblaba como ramas flexibles. Aenar caminó entre torres que reflejaban futuros posibles, sintiendo que cada segundo lo evaluaba.El espejo reaccionó de inmediato.Cuando lo abrió, vio una versión de sí mismo viviendo en un futuro donde Hollowreach había muerto.Esa versión estaba hecha de ceniza.Su piel era polvo.Sus ojos eran huecos.—Tú lo abandonaste —dijo el reflejo—. Y el bosque murió sin ti.Las calles cambiaron de lugar, acercándolo al espejo.El tiempo quería que Aenar viera su culpa.Quería que entendiera que su rechazo al legado había tenido consecuencias.El reflejo extendió una mano hecha de ceniza.Cuando tocó el cristal, Aenar sintió que su corazón se volvía polvo.El tiempo no quería castigarlo.Quería repetirlo.",
            "Maridia Azul":"Maridia Azul brillaba como un corazón marino. Aenar nunca había sentido afinidad por el océano, pero el espejo sí.Cuando lo abrió, la superficie se llenó de agua.Su reflejo era un tronco flotante, viajando por mareas.Tenía ojos de madera, pero su cuerpo era líquido.Era naturaleza… pero no bosque.—La naturaleza no es solo raíces —dijo el reflejo—. También es corriente.Las criaturas luminosas bajo la ciudad se acercaron, atraídas por el espejo.El agua se derramó, formando una figura vegetal que caminó hacia él.Aenar sintió que su magia, aquella que había intentado ocultar toda su vida, reaccionaba al océano.Que su poder no era solo terrestre.Que podía extenderse más allá del bosque.El mar no quería un guardabosques.Quería un árbol que flotara entre mundos.",
            "Elderwood Crown":"Elderwood Crown era el corazón del bosque.Aenar sintió que el lugar lo reconocía, como si las raíces supieran su nombre desde antes de que él naciera.Cuando abrió el espejo, vio una versión de sí mismo sentado en la Corona Arbórea.Era rey vegetal.Era soberano del bosque.Era raíz y tronco y savia.El reflejo extendió raíces hacia él.—El bosque te eligió hace generaciones —dijo—. No puedes negarlo.Las calles vivas se cerraron detrás de Aenar, obligándolo a avanzar.El árbol central vibró, como si esperara su llegada.Aenar sintió que su magia despertaba, que su cuerpo quería fusionarse con la corteza viva.Elderwood Crown no quería un descendiente.Quería un monarca vegetal.",
        },

        "La corona de espinas vivas":
        {
            "Hollowreach":"La corona estaba enterrada bajo raíces negras, como si el bosque hubiera intentado ocultarla de sí mismo.Cuando Aenar la tocó, las espinas se despertaron.Se la colocó.El bosque gritó.Las espinas se hundieron en su cráneo, pero no para herirlo: para activarlo.Aenar sintió raíces creciendo bajo su piel, extendiéndose por sus brazos, conectándolo al bosque entero.Podía sentir cada árbol.Cada raíz.Cada criatura vegetal.Era el guardabosques perfecto.Pero cada segundo drenaba su vida.La corona bebía de él.Primero minutos.Luego horas.Luego días.Cuando intentó quitársela, las espinas ya eran parte de él.Hollowreach no quería un protector.Quería un corazón humano para alimentarse.",
            "Aurelia Tempus":"La corona reaccionó a la ciudad temporal como si fuera un reloj vegetal.Cada campanada del Gran Reloj aceleraba su vida.Cada segundo lo envejecía.Aenar vivía y moría en ciclos dolorosos.Su magia se expandía y se contraía.El tiempo lo moldeaba como arcilla.Pero a cambio, podía controlar el tiempo del bosque.Podía detener la muerte que avanzaba por Hollowreach.Podía suspender la corrupción.La corona floreció con cada uso, brotando hojas negras que caían como ceniza.Aenar envejecía y rejuvenecía en segundos.Cuando el Gran Reloj marcó una hora imposible, la corona se abrió como una flor de espinas.Aenar sintió cómo cien años se evaporaban de su cuerpo en un solo latido.La ciudad no quería su vida.Quería su tiempo vegetal.",
            "Maridia Azul":"La bruma marina envolvió la corona, y las espinas reaccionaron como si despertaran de un sueño profundo.Absorbieron humedad.Se hincharon.Se movieron.Cuando Aenar se la colocó, las mareas cambiaron.Las plataformas se inclinaron.Las criaturas luminosas ascendieron.El océano lo reconocía.Pero la corona tenía hambre.Las espinas crecieron hacia dentro, buscando su corazón.Cada vez que Aenar controlaba una corriente, una ola, una criatura marina, la corona drenaba parte de su magia.Cuando calmó una tormenta, sintió que olvidaba el rostro de su familia por un instante.La corona floreció, satisfecha.El mar lo quería como guardián.La corona lo quería como sacrificio vegetal.",
            "Elderwood Crown":"Elderwood Crown reaccionó a la corona como si fuera una reliquia perdida.Los árboles colosales se inclinaron.Las calles vivas se abrieron.La Corona Arbórea vibró.Cuando Aenar se la colocó, las espinas se fusionaron con la corteza viva del lugar.No lo herían: lo integraban.Aenar sintió raíces creciendo bajo su piel, extendiéndose por sus brazos, conectándolo al árbol central.Por primera vez, comprendió el lenguaje completo del bosque.Elderwood Crown no quería un guardabosques.Quería un corazón nuevo.",
        },

        "La copa del cielo":
        {
            "Hollowreach":"Aenar vertió savia del bosque en la copa.La savia se volvió dorada.Al beber, vio el momento exacto en que su familia desapareció.No fue accidente.No fue destino.Fue traición.Vio sombras humanas cortando raíces vivas, enterrando algo bajo el bosque.Vio a los Woodbound luchando.Vio su caída.Cuando la visión terminó, el bosque gritó.No eran voces.Eran advertencias.La copa había revelado la verdad.Y ahora aquello que vivía bajo las raíces sabía que Aenar lo había visto.",
            "Aurelia Tempus":"La copa se llenó sola con luz líquida.Cuando Aenar bebió, vio futuros donde él salvaba Hollowreach… y futuros donde él lo destruía.En todos, su magia era el detonante.En todos, su legado era la clave.El Gran Reloj vibró, como si reconociera su poder.Las calles cambiaron de lugar, guiándolo hacia el centro.La copa reveló que el tiempo no quería que él fuera guardabosques.Quería que fuera arma.",
            "Maridia Azul":"La copa se llenó con agua luminosa.Cuando Aenar bebió, vio que el océano tenía raíces.Raíces profundas.Raíces vivas.Vio corrientes conectando mar y bosque.Vio criaturas marinas moviéndose entre troncos.Vio que su magia podía extenderse más allá de Hollowreach.El mar no quería un guardabosques.Quería un árbol que respirara agua.",
            "Elderwood Crown":"La copa se llenó con savia dorada.Cuando Aenar bebió, vio que el árbol central quería convertirlo en su corazón.No como sacrificio.Como reemplazo.Vio raíces moviéndose hacia él.Vio corteza abriéndose.Vio savia buscando su sangre.Elderwood Crown no quería un descendiente.Quería un renacimiento.",
        },

        "La llama de hueso":
        {
            "Hollowreach":"La llama reveló que el bosque tenía partes muertas que seguían moviéndose.Aenar intentó controlarlas.Ellas intentaron controlarlo.Las raíces muertas se levantaron, formando figuras humanas.Sombras vegetales con ojos vacíos.Ecos de los Woodbound.La llama rugió.El bosque respondió.Aenar sintió que la muerte en Hollowreach tenía memoria.Y que esa memoria lo quería a él.",
            "Aurelia Tempus":"La llama mostró horas muertas que seguían latiendo.Aenar vio sombras de antiguos Woodbound atrapadas en segundos rotos.Vio sus rostros.Vio su caída.Una de ellas se acercó.Tenía su apellido.Tenía su voz.El tiempo rugió.La llama respondió.Aurelia Tempus no quería su magia.Quería su linaje.",
            "Maridia Azul":"La llama reveló criaturas marinas muertas que seguían nadando.Una tenía forma de raíz.Otra tenía forma de tronco.Otra tenía su rostro.El mar rugió.La llama respondió.Aenar sintió que el océano tenía cadáveres que aún respiraban.Y que algunos querían reemplazarlo.",
            "Elderwood Crown":"La llama reveló que el árbol central tenía un corazón muerto… pero seguía latiendo.Aenar escuchó su nombre dentro del latido.Un nombre vegetal.Un nombre humano.El árbol rugió.Las raíces se levantaron.La corteza se abrió.Elderwood Crown no quería un guardabosques.Quería un corazón Woodbound.",
        }
    }
}